const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const kaggleService = require('./kaggleService');

const STUDIO_RUNTIME_DIR = path.resolve(
  process.env.KAGGLE_STUDIO_RUNTIME_DIR || path.join(__dirname, '.runtime', 'kaggle-studio')
);
const SESSIONS_DIR = path.join(STUDIO_RUNTIME_DIR, 'sessions');
const BACKUPS_DIR = path.join(STUDIO_RUNTIME_DIR, 'backups');
const TEMPLATE_PATH = path.resolve(
  process.env.KAGGLE_STUDIO_TEMPLATE_PATH || path.join(__dirname, 'scripts', 'kaggle_codex_studio_v21.py')
);
const MAX_CALLBACK_TEXT = 12000;

for (const dir of [STUDIO_RUNTIME_DIR, SESSIONS_DIR, BACKUPS_DIR]) {
  fs.mkdirSync(dir, { recursive: true });
}

function nowIso() {
  return new Date().toISOString();
}

function clampInt(value, fallback, min, max) {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.max(min, Math.min(max, parsed));
}

function normalizeSlugList(value) {
  const list = Array.isArray(value)
    ? value
    : String(value || '')
        .split(/[\n,]+/)
        .map((entry) => entry.trim())
        .filter(Boolean);
  return [...new Set(list.map((entry) => String(entry).trim()).filter((entry) => /^[a-z0-9_.-]+\/[a-z0-9_.-]+$/i.test(entry)))].slice(0, 20);
}

function sanitizeStudioOptions(raw = {}) {
  const gpuPreference = ['none', 't4', 'p100', 'any'].includes(String(raw.gpuPreference || '').toLowerCase())
    ? String(raw.gpuPreference).toLowerCase()
    : 't4';
  const tunnelProvider = ['pinggy', 'auto', 'localhostrun', 'ngrok', 'none'].includes(String(raw.tunnelProvider || '').toLowerCase())
    ? String(raw.tunnelProvider).toLowerCase()
    : 'pinggy';
  const enableInternet = raw.enableInternet !== false;
  const persistenceEnabled = raw.persistenceEnabled !== false;
  return {
    gpuPreference,
    enableInternet,
    persistenceEnabled,
    backupIntervalMinutes: clampInt(raw.backupIntervalMinutes, 10, 3, 120),
    maxBackupMb: clampInt(raw.maxBackupMb, 300, 25, 1024),
    maxParallel: clampInt(raw.maxParallel, 1, 1, 4),
    tunnelProvider,
    datasetSources: normalizeSlugList(raw.datasetSources),
    publicBaseUrl: String(raw.publicBaseUrl || '').trim().replace(/\/+$/, ''),
    title: String(raw.title || 'Codex Studio').trim().slice(0, 80) || 'Codex Studio'
  };
}

function assertSessionId(value) {
  const id = String(value || '').trim();
  if (!/^studio-[a-f0-9]{12}$/i.test(id)) throw new Error('Invalid studio session id');
  return id;
}

function statePath(sessionId) {
  return path.join(SESSIONS_DIR, `${assertSessionId(sessionId)}.json`);
}

function backupPath(sessionId) {
  return path.join(BACKUPS_DIR, `${assertSessionId(sessionId)}.zip`);
}

function writeJsonAtomic(filePath, value) {
  const tmpPath = `${filePath}.${process.pid}.${crypto.randomBytes(4).toString('hex')}.tmp`;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(tmpPath, JSON.stringify(value, null, 2), 'utf8');
  fs.renameSync(tmpPath, filePath);
}

function loadState(sessionId) {
  const filePath = statePath(sessionId);
  if (!fs.existsSync(filePath)) return null;
  try {
    const parsed = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch (_error) {
    return null;
  }
}

function saveState(state) {
  const next = { ...state, updatedAt: nowIso() };
  writeJsonAtomic(statePath(next.id), next);
  return next;
}

function hashToken(token) {
  return crypto.createHash('sha256').update(String(token || '')).digest('hex');
}

function timingSafeTokenMatch(state, token) {
  const expected = Buffer.from(String(state?.tokenHash || ''), 'hex');
  const actual = Buffer.from(hashToken(token), 'hex');
  return expected.length === actual.length && expected.length > 0 && crypto.timingSafeEqual(expected, actual);
}

function publicSession(state) {
  if (!state) return null;
  const { tokenHash, ownerUserId, ...safe } = state;
  const backup = backupPath(state.id);
  return {
    ...safe,
    backupAvailable: fs.existsSync(backup),
    backupBytes: fs.existsSync(backup) ? fs.statSync(backup).size : 0
  };
}

function renderEnvAssignments(values) {
  return Object.entries(values)
    .map(([key, value]) => `os.environ[${JSON.stringify(key)}] = ${JSON.stringify(String(value ?? ''))}`)
    .join('\n');
}

function buildStudioKernelCode({ sessionId, token, options, callbackUrl, controlUrl, backupUrl }) {
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');
  const envHead = `# Generated by CodexWeb Kaggle Studio\nimport os\n${renderEnvAssignments({
    CODEXWEB_STUDIO_SESSION_ID: sessionId,
    CODEXWEB_STUDIO_TOKEN: token,
    CODEXWEB_STUDIO_CALLBACK_URL: callbackUrl,
    CODEXWEB_STUDIO_CONTROL_URL: controlUrl,
    CODEXWEB_STUDIO_BACKUP_URL: backupUrl,
    CODEXWEB_STUDIO_GPU_PREFERENCE: options.gpuPreference,
    CODEXWEB_STUDIO_PERSISTENCE: options.persistenceEnabled ? '1' : '0',
    CODEXWEB_STUDIO_BACKUP_INTERVAL_SECONDS: options.backupIntervalMinutes * 60,
    CODEXWEB_STUDIO_MAX_BACKUP_MB: options.maxBackupMb,
    KAGGLE_TUNNEL_PROVIDER: options.tunnelProvider,
    KAGGLE_CODEX_MAX_PARALLEL: options.maxParallel
  })}\n\n`;

  const controlTail = String.raw`

# ─────────────────────────────────────────────────────────────
# CodexWeb control plane: callback, heartbeat, persistence and cooperative stop.
# The Kaggle public API does not give CodexWeb a dependable live-process kill switch,
# so the running kernel polls a token-protected endpoint and exits cleanly on request.
# ─────────────────────────────────────────────────────────────
import io as _cw_io, json as _cw_json, zipfile as _cw_zipfile, tempfile as _cw_tempfile
import urllib.request as _cw_request, urllib.error as _cw_error

_CW_SESSION = os.environ.get("CODEXWEB_STUDIO_SESSION_ID", "")
_CW_TOKEN = os.environ.get("CODEXWEB_STUDIO_TOKEN", "")
_CW_CALLBACK = os.environ.get("CODEXWEB_STUDIO_CALLBACK_URL", "")
_CW_CONTROL = os.environ.get("CODEXWEB_STUDIO_CONTROL_URL", "")
_CW_BACKUP = os.environ.get("CODEXWEB_STUDIO_BACKUP_URL", "")
_CW_PERSIST = os.environ.get("CODEXWEB_STUDIO_PERSISTENCE", "0") == "1"
_CW_BACKUP_INTERVAL = max(180, int(os.environ.get("CODEXWEB_STUDIO_BACKUP_INTERVAL_SECONDS", "600") or "600"))
_CW_MAX_BACKUP = max(25, int(os.environ.get("CODEXWEB_STUDIO_MAX_BACKUP_MB", "300") or "300")) * 1024 * 1024

def _cw_headers(content_type="application/json"):
    return {"Authorization": "Bearer " + _CW_TOKEN, "Content-Type": content_type, "User-Agent": "CodexWeb-Kaggle-Studio/1"}

def _cw_json_request(url, method="GET", payload=None, timeout=20):
    if not url or not _CW_TOKEN:
        return {}
    data = None if payload is None else _cw_json.dumps(payload).encode("utf-8")
    req = _cw_request.Request(url, data=data, method=method, headers=_cw_headers())
    try:
        with _cw_request.urlopen(req, timeout=timeout) as response:
            raw = response.read()
            return _cw_json.loads(raw.decode("utf-8")) if raw else {}
    except Exception as exc:
        log("[control] request failed: " + repr(exc))
        return {}

def _cw_gpu_name():
    try:
        result = subprocess.run(["nvidia-smi", "--query-gpu=name", "--format=csv,noheader"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=15)
        return ", ".join(line.strip() for line in (result.stdout or "").splitlines() if line.strip()) or "none"
    except Exception:
        return "none"

def _cw_notify(event, **payload):
    body = {"event": event, "sessionId": _CW_SESSION, "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), **payload}
    _cw_json_request(_CW_CALLBACK, "POST", body, 20)

def _cw_safe_extract(zip_path, target):
    target = pathlib.Path(target).resolve()
    with _cw_zipfile.ZipFile(zip_path, "r") as archive:
        for member in archive.infolist():
            destination = (target / member.filename).resolve()
            if destination != target and target not in destination.parents:
                raise RuntimeError("unsafe backup path")
        archive.extractall(target)

def _cw_restore_workspace():
    if not _CW_PERSIST or not _CW_BACKUP:
        return
    req = _cw_request.Request(_CW_BACKUP, method="GET", headers=_cw_headers("application/octet-stream"))
    try:
        with _cw_request.urlopen(req, timeout=60) as response:
            data = response.read(_CW_MAX_BACKUP + 1)
        if not data or len(data) > _CW_MAX_BACKUP:
            return
        with _cw_tempfile.NamedTemporaryFile(suffix=".zip", delete=False) as tmp:
            tmp.write(data); temp_name = tmp.name
        try:
            _cw_safe_extract(temp_name, WORKSPACE)
            log("[control] workspace restored from CodexWeb")
        finally:
            pathlib.Path(temp_name).unlink(missing_ok=True)
    except _cw_error.HTTPError as exc:
        if exc.code != 404: log("[control] restore failed: " + repr(exc))
    except Exception as exc:
        log("[control] restore failed: " + repr(exc))

def _cw_backup_workspace():
    if not _CW_PERSIST or not _CW_BACKUP:
        return False
    buffer = _cw_io.BytesIO()
    skipped = {".git", "node_modules", "__pycache__", ".cache", ".venv", "venv"}
    try:
        with _cw_zipfile.ZipFile(buffer, "w", _cw_zipfile.ZIP_DEFLATED, allowZip64=True) as archive:
            for file_path in WORKSPACE.rglob("*"):
                if not file_path.is_file():
                    continue
                rel = file_path.relative_to(WORKSPACE)
                if any(part in skipped for part in rel.parts):
                    continue
                archive.write(file_path, rel.as_posix())
                if buffer.tell() > _CW_MAX_BACKUP:
                    raise RuntimeError("workspace backup exceeds configured limit")
        data = buffer.getvalue()
        req = _cw_request.Request(_CW_BACKUP, data=data, method="POST", headers=_cw_headers("application/zip"))
        with _cw_request.urlopen(req, timeout=120) as response:
            response.read()
        log("[control] workspace backup uploaded: " + str(len(data)) + " bytes")
        return True
    except Exception as exc:
        log("[control] backup failed: " + repr(exc))
        return False

# Restore is deliberately executed after the app bootstrap in v21. It restores user workspace
# files without replacing the generated runtime or authentication state.
_cw_restore_workspace()
_cw_notify(
    "ready",
    publicUrl=public_url or "",
    tunnelProvider=tunnel_provider,
    localUrl="http://127.0.0.1:" + str(port),
    actualGpu=_cw_gpu_name(),
    requestedGpu=os.environ.get("CODEXWEB_STUDIO_GPU_PREFERENCE", "any"),
    workspace=str(WORKSPACE),
)

_last_heartbeat = 0.0
_last_backup = time.time()
_stop_reason = ""
try:
    while True:
        if proc.poll() is not None:
            _stop_reason = "uvicorn_exited"
            _cw_notify("error", error="El servidor interno de Codex Studio terminó", exitCode=proc.returncode)
            break
        now = time.time()
        if now - _last_heartbeat >= 15:
            control = _cw_json_request(_CW_CONTROL, "GET", None, 15)
            _last_heartbeat = now
            _cw_notify("heartbeat", publicUrl=public_url or "", actualGpu=_cw_gpu_name(), uptimeSeconds=int(now-started))
            if control.get("stopRequested"):
                _stop_reason = str(control.get("reason") or "requested_from_codexweb")
                _cw_notify("stopping", reason=_stop_reason)
                break
        if _CW_PERSIST and now - _last_backup >= _CW_BACKUP_INTERVAL:
            _cw_backup_workspace(); _last_backup = now
        time.sleep(1)
except KeyboardInterrupt:
    _stop_reason = "keyboard_interrupt"
finally:
    if _CW_PERSIST:
        _cw_backup_workspace()
    try:
        proc.terminate(); proc.wait(timeout=10)
    except Exception:
        try: proc.kill()
        except Exception: pass
    try: kill_old()
    except Exception: pass
    _cw_notify("stopped", reason=_stop_reason or "kernel_finished")
`;

  return `${envHead}${template}${controlTail}`;
}

async function startSession(rawOptions, requestBaseUrl, ownerUserId) {
  const safeOwnerUserId = Number(ownerUserId);
  if (!Number.isInteger(safeOwnerUserId) || safeOwnerUserId <= 0) {
    throw Object.assign(new Error('Invalid CodexWeb user for Kaggle Studio'), { statusCode: 400 });
  }
  const existingActive = listSessionStates(safeOwnerUserId).find((entry) =>
    ['launching', 'queued', 'pending', 'running', 'stopping'].includes(String(entry.status || ''))
  );
  if (existingActive) {
    throw Object.assign(new Error('Ya hay una sesión de Codex Studio activa para este usuario'), { statusCode: 409 });
  }
  const options = sanitizeStudioOptions(rawOptions);
  const baseUrl = String(options.publicBaseUrl || requestBaseUrl || '').trim().replace(/\/+$/, '');
  if (!/^https?:\/\//i.test(baseUrl)) {
    throw new Error('No se pudo determinar una URL pública de CodexWeb para callbacks de Kaggle. Configura CODEXWEB_PUBLIC_URL o publicBaseUrl.');
  }

  const sessionId = `studio-${crypto.randomBytes(6).toString('hex')}`;
  const token = crypto.randomBytes(32).toString('hex');
  let state = saveState({
    id: sessionId,
    status: 'launching',
    createdAt: nowIso(),
    tokenHash: hashToken(token),
    ownerUserId: safeOwnerUserId,
    stopRequested: false,
    options: { ...options, publicBaseUrl: baseUrl },
    publicUrl: '',
    tunnelProvider: '',
    actualGpu: '',
    lastHeartbeatAt: ''
  });

  const callbackUrl = `${baseUrl}/api/kaggle/studio/callback/${sessionId}`;
  const controlUrl = `${baseUrl}/api/kaggle/studio/control/${sessionId}`;
  const backupUrl = `${baseUrl}/api/kaggle/studio/backup/${sessionId}`;
  const code = buildStudioKernelCode({ sessionId, token, options, callbackUrl, controlUrl, backupUrl });
  const result = await kaggleService.submitJob(code, {
    title: `${options.title} ${sessionId}`,
    enableGpu: options.gpuPreference !== 'none',
    enableInternet: options.enableInternet,
    datasetSources: options.datasetSources,
    studioSessionId: sessionId
  });

  if (!result.success) {
    state = saveState({ ...state, status: 'error', error: result.error || 'No se pudo enviar el kernel a Kaggle', details: result.stderr || '' });
    return publicSession(state);
  }

  state = saveState({
    ...state,
    status: 'queued',
    jobId: result.jobId,
    kaggleRef: result.kaggleRef,
    launchMessage: result.message || 'Job enviado a Kaggle'
  });
  return publicSession(state);
}

async function refreshSession(sessionId, ownerUserId = null) {
  let state = loadState(sessionId);
  if (!state || (ownerUserId != null && Number(state.ownerUserId) !== Number(ownerUserId))) return null;
  if (!state.jobId || ['stopped', 'error', 'complete'].includes(state.status)) return publicSession(state);
  try {
    const statusResult = await kaggleService.getJobStatus(state.jobId);
    if (statusResult.success) {
      const remoteStatus = String(statusResult.status || 'unknown');
      const terminal = ['complete', 'error', 'cancelled'].includes(remoteStatus);
      const hasRecentHeartbeat = state.lastHeartbeatAt && Date.now() - Date.parse(state.lastHeartbeatAt) < 45000;
      let nextStatus = state.status;
      if (terminal && !hasRecentHeartbeat) nextStatus = remoteStatus === 'cancelled' ? 'stopped' : remoteStatus;
      else if (!hasRecentHeartbeat && ['running', 'queued', 'pending'].includes(remoteStatus)) nextStatus = remoteStatus;
      state = saveState({ ...state, status: nextStatus, kaggleStatus: remoteStatus, kaggleStatusRaw: statusResult.raw || '' });
    }
  } catch (error) {
    state = saveState({ ...state, statusCheckError: String(error?.message || error) });
  }
  return publicSession(state);
}

function listSessionStates(ownerUserId = null) {
  return fs.readdirSync(SESSIONS_DIR)
    .filter((name) => name.endsWith('.json'))
    .map((name) => loadState(name.slice(0, -5)))
    .filter((entry) => Boolean(entry) && (ownerUserId == null || Number(entry.ownerUserId) === Number(ownerUserId)))
    .sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt)));
}

function listSessions(ownerUserId = null) {
  return listSessionStates(ownerUserId).map(publicSession);
}

function requireToken(sessionId, token) {
  const state = loadState(sessionId);
  if (!state) throw Object.assign(new Error('Studio session not found'), { statusCode: 404 });
  if (!timingSafeTokenMatch(state, token)) throw Object.assign(new Error('Invalid studio token'), { statusCode: 401 });
  return state;
}

function applyCallback(sessionId, token, payload = {}) {
  let state = requireToken(sessionId, token);
  const event = String(payload.event || '').trim().toLowerCase();
  const update = {
    lastCallbackAt: nowIso(),
    lastEvent: event,
    callbackMessage: String(payload.message || payload.error || '').slice(0, MAX_CALLBACK_TEXT)
  };
  if (payload.publicUrl && /^https?:\/\//i.test(String(payload.publicUrl))) update.publicUrl = String(payload.publicUrl).slice(0, 2048);
  if (payload.tunnelProvider) update.tunnelProvider = String(payload.tunnelProvider).slice(0, 40);
  if (payload.actualGpu) update.actualGpu = String(payload.actualGpu).slice(0, 300);
  if (payload.localUrl) update.localUrl = String(payload.localUrl).slice(0, 300);
  if (payload.workspace) update.workspace = String(payload.workspace).slice(0, 500);
  if (Number.isFinite(Number(payload.uptimeSeconds))) update.uptimeSeconds = Number(payload.uptimeSeconds);
  if (event === 'ready' || event === 'heartbeat') {
    update.status = state.stopRequested ? 'stopping' : 'running';
    update.lastHeartbeatAt = nowIso();
    update.error = '';
  } else if (event === 'stopping') {
    update.status = 'stopping';
  } else if (event === 'stopped') {
    update.status = 'stopped';
    update.stoppedAt = nowIso();
  } else if (event === 'error') {
    update.status = 'error';
    update.error = String(payload.error || payload.message || 'Kaggle Studio error').slice(0, MAX_CALLBACK_TEXT);
  }
  state = saveState({ ...state, ...update });
  return publicSession(state);
}

function getControl(sessionId, token) {
  const state = requireToken(sessionId, token);
  return {
    ok: true,
    sessionId: state.id,
    stopRequested: Boolean(state.stopRequested),
    reason: state.stopReason || '',
    requestedAt: state.stopRequestedAt || ''
  };
}

function requestStop(sessionId, reason = 'requested_from_codexweb', ownerUserId = null) {
  let state = loadState(sessionId);
  if (!state || (ownerUserId != null && Number(state.ownerUserId) !== Number(ownerUserId))) return null;
  if (['stopped', 'complete', 'error'].includes(state.status)) return publicSession(state);
  state = saveState({
    ...state,
    status: 'stopping',
    stopRequested: true,
    stopReason: String(reason || 'requested_from_codexweb').slice(0, 300),
    stopRequestedAt: nowIso()
  });
  return publicSession(state);
}

function saveBackup(sessionId, token, buffer) {
  const state = requireToken(sessionId, token);
  const maxBytes = Number(state.options?.maxBackupMb || 300) * 1024 * 1024;
  if (!Buffer.isBuffer(buffer) || !buffer.length) throw Object.assign(new Error('Empty backup'), { statusCode: 400 });
  if (buffer.length > maxBytes) throw Object.assign(new Error('Backup too large'), { statusCode: 413 });
  const filePath = backupPath(sessionId);
  const tmpPath = `${filePath}.${process.pid}.tmp`;
  fs.writeFileSync(tmpPath, buffer);
  fs.renameSync(tmpPath, filePath);
  saveState({ ...state, lastBackupAt: nowIso(), lastBackupBytes: buffer.length });
  return { ok: true, bytes: buffer.length };
}

function getBackup(sessionId, token) {
  requireToken(sessionId, token);
  const filePath = backupPath(sessionId);
  return fs.existsSync(filePath) ? filePath : null;
}

module.exports = {
  sanitizeStudioOptions,
  buildStudioKernelCode,
  startSession,
  refreshSession,
  listSessions,
  loadState,
  publicSession,
  applyCallback,
  getControl,
  requestStop,
  saveBackup,
  getBackup,
  requireToken,
  TEMPLATE_PATH,
  STUDIO_RUNTIME_DIR
};
